[package]
name = "roller"
version = "0.1.0"
authors = ["Derrek <dschuurm@ucsd.edu>"]
edition = "2018"
description = "a simple dice rolling tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"